### ISSUE TITLE
Mac binary has a very poor backwards compatibility (deployment target)

### ISSUE THREAD

**Issue by Grix** [time-killer-games/libdlgmod#3] opened 2023-11-05 13:04 UTC
As mentioned in a recent email, I have received numerous reports from users that dialogs are not showing up when they use my software that uses this library, on various macOS versions. 
I suspected that it was because it was compiled with a very recent deployment target, and after checking with otool on the dylib I think I have confirmed this, as the "minos" attribute was 13.0. 
If I understand correctly means that the library will not work for macOS versions older than Ventura, which is barely a year old and thus still has many people yet to update. In fact, some users literally cannot update since their hardware is locked out of such new versions by Apple. 

It would be great if the mac binaries could be recompiled with an older deployment target, preferably as far back as 10.13 (high sierra). Probably there would be no required code changes, just a compiler flag. I would compile it myself but I am unable to do so, I get errors when running build.sh.

**Comment by time-killer-games** [comment] 2023-11-05 17:40
I don't intend on installing older versions of MacOS on top of the current release if it is just a matter of rebuilding the dylib and dlgmod executable from source. This is very easy to do and is just a matter of running the build.sh script from the terminal for my libdlgmod repository. If you use asnync dialogs, you will also need to rebuild the dlgmod executable from the dlgmod repository (the one without the "lib" prefix). However, if you run into build errors I will be willing to install an outdated version of MacOS for the sake of doing a special build for you, though it will not be a part of my main repository or releases any new binaries or code changes I make to accommodate those older versions of macOS.

Note, Apple, unlike windows. changes their API and ABI compatibility quickly and abruptly. It is way too much work for me to support anything besides the latest release for most of my extensions as the code will need conditional changes based on what the current OS version is in use, and that is why I do not like Apple, one of many reasons.

Let me know on discord if you need help building it or if you get build errors so I can further make accommodations, though note, there is a limit on how many versions of macOS I will be ok with supporting. No more than what GM supports natively, perhaps less than that depending on the amount of conditional code I will have to write per OS version.

My discord handle is `@samuelvenable` though you might already have me as a friend on there. I can't remember.

**Comment by time-killer-games** [comment] 2023-11-05 17:59
Scratch what I said previously, under the circumstances you might actually be able to compile with a slight modification to the build script like you suspected and without code changes. It is worth a shot, but I will need to know what error the build script is giving you. Always remember to provide exact errors being thrown when reporting issues of any kind, on any bug tracker or feature request. :)

**Comment by Grix** [comment] 2023-11-06 08:59
Thank you for the advice, indeed removing `-arch arm64` from the build script fixed the errors. (But does that mean that it cannot run on the arm M-series cpu's?)

Adding the clang flag `-mmacosx-version-min=10.13` to the script changed the deployment target successfully. 

However I also found that the default binaries of SDL2 installed from brew also had a very recent deployment target, so I got more compiler warnings. So what I had to do is download the source of SDL2 and build that too with an older deployment target (actually the source was already set up for an old deployment target so it was plug and play).

So I understand if you don't want to bother doing this for the official version. But as far as I'm concerned, the issue is fixed.

**Comment by time-killer-games** [comment] 2023-11-06 09:30
Hey! I'm glad to hear that everything worked out for you. Feel free to share the binaries you made in an attachment here, and I can leave this issue open indefinitely to help visibility for other users with the same concerns. :)

**Comment by time-killer-games** [comment] 2023-11-14 14:37
@Grix On macOS the file and directory selection dialogs are powered by SDL2 and Dear ImGui as you probably know. As a result on macOS the file and directory selection dialogs are much more customizable.

For example, you can do this:
```
environment_set_variable("IMGUI_FONT_FILES", working_directory + "Righteous-Regular.ttf");
environment_set_variable("IMGUI_DIALOG_THEME", string(2));
environment_set_variable("IMGUI_TEXT_COLOR_0", string(1));
environment_set_variable("IMGUI_TEXT_COLOR_2", string(1));
environment_set_variable("IMGUI_TEXT_COLOR_1", string(1));
environment_set_variable("IMGUI_HEAD_COLOR_0", string(0));
environment_set_variable("IMGUI_HEAD_COLOR_2", string(1));
environment_set_variable("IMGUI_HEAD_COLOR_1", string(0));
environment_set_variable("IMGUI_AREA_COLOR_0", string(0));
environment_set_variable("IMGUI_AREA_COLOR_2", string(0.25));
environment_set_variable("IMGUI_AREA_COLOR_1", string(0));
environment_set_variable("IMGUI_BODY_COLOR_0", string(0));
environment_set_variable("IMGUI_BODY_COLOR_2", string(0.12));
environment_set_variable("IMGUI_BODY_COLOR_1", string(0));
environment_set_variable("IMGUI_POPS_COLOR_0", string(0));
environment_set_variable("IMGUI_POPS_COLOR_2", string(0.12));
environment_set_variable("IMGUI_POPS_COLOR_1", string(0));
get_open_filename("", "");
```

And it will have a custom font and color scheme, looking like this:

![Screenshot_20230612_062815](https://github.com/time-killer-games/libdlgmod/assets/4379204/b6f28316-e5e5-4c74-9d5e-b370a5aa6f5a)

Which the above example uses this font file:

[Righteous.zip](https://github.com/time-killer-games/libdlgmod/files/13349890/Righteous.zip)

To support multiple languages, you can use multiple font paths and combine the fonts by passing the path to the environment variable, like so (line feed separated):

```
// Delimiter for Multiple Fonts is Line Feed ("\n"):
environment_set_variable("IMGUI_FONT_FILES", 
working_directory + "Righteous-Regular.ttf\n" + 
working_directory + "NotoSansArabic-Regular.ttf\n"
working_directory + "NotoSansSC-Regular.otf\n"
working_directory + "NotoSansJP-Regular.otf");
```

The Noto Sans font collection is known support all UTF-8 characters, if you happen to include the entire collection of font files it has, which is included with my dialog module asset under included files. Note the more fonts you include (especially one with a lot of characters like Chinese Simplified) will take longer to load and increase the amount of time for the dialog to appear.

**Comment by time-killer-games** [comment] 2024-04-12 18:05
It's ok! I understand completely. At some point or another I am going to need to get a High Sierra VM up and running to check out for myself what could be the issue. Were there problems only happening with the async dialogs or was it a problem with the synchronous as well? If you only tested one or the other and don't wish to test further that is perfectly ok. Thank you for the bug reports.

**Comment by Grix** [comment] 2024-04-12 18:20
I used the synchronous functions. 
And please note that while this original bug thread was for older macOS compatibility, that's just for the sake of my users, not me. My test now was on a modern macOS version, not high sierra.

**Comment by time-killer-games** [comment] 2024-04-12 18:30
I see. That's interesting. I'm unable to reproduce the bugs you had on my end. I wonder what we're doing differently from each other on the GML side. For the High Sierra-specific code, I did find some technically incorrect things with the code, it's partially fixed now, but from the sound of what you are saying, this extension is still pretty broken on Mac regardless of the version of macOS. Thanks for the heads up, I've got quite a wild goose chase to investigate for everyone else using this extension. But that's my fault, obviously, for writing such buggy software.

**Comment by Grix** [comment] 2024-04-12 18:34
If you upload a sample GM project that works for you, then when I have time I can try testing it to see whether it works and it was just some project/GML difference after all, or if indeed that doesn't work for me either.

**Comment by time-killer-games** [comment] 2024-04-12 20:23
Here's my project which works for me:

https://drive.google.com/drive/folders/182Vo2GtbQugAiN0wEd68HJ64I7LMrTmr?usp=share_link

I am also using this extension in Minecraft Note Block Studio, as a more elaborate example of it working:

https://github.com/time-killer-games/OpenNoteBlockStudio/releases/tag/v0.0.0.0

(Requires Rosetta installed for the pre-built binary).

**Comment by Grix** [comment] 2024-04-13 16:38
Good news, I tested the project you linked and it works just fine. 
So the problem with the original attempt was indeed probably something on my end, even though I don't know what.

**Comment by time-killer-games** [comment] 2024-04-15 04:20
It could be the changes I made, when we were in the middle of talking the other day, which may have been what fixed it.

But yeah, no idea. Just glad it works.

**Comment by time-killer-games** [comment] 2024-04-17 19:46
> Good news, I tested the first project you linked and it works just fine. So the problem with the original attempt was indeed probably something on my end, even though I don't know what.

Sorry to bother you again. One last thing I wanted to ask. I was wondering if I could have a link to the project you are using this extension in? If it is commercial I'll likely buy it just to see my work in action, depending on the price.

**Closed by time-killer-games** 2024-04-17 19:46 UTC

**Comment by Grix** [comment] 2024-04-18 06:26
> > Good news, I tested the first project you linked and it works just fine. So the problem with the original attempt was indeed probably something on my end, even though I don't know what.
> 
> Sorry to bother you again. One last thing I wanted to ask. I was wondering if I could have a link to the game or app you are using this extension in? If it is commercial I'll likely buy it just to see my work in action, depending on the price.

Haha, thanks for the interest, it is this: https://bitlasers.com/lasershowgen-sw/

No need to buy it, there is a free version.
